/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/base/Button.vue')['default']
    ButtonBase: typeof import('./src/components/base/icon/ButtonBase.vue')['default']
    ButtonComp: typeof import('./src/components/base/icon/ButtonComp.vue')['default']
    ButtonCompExtends: typeof import('./src/components/base/icon/ButtonCompExtends.vue')['default']
    DefineModel: typeof import('./src/components/demo/DefineModel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: (typeof import('element-plus/es'))['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: (typeof import('element-plus/es'))['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FilterForm: typeof import('./src/components/business/table/FilterForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAliOthers: typeof import('~icons/ali/others')['default']
    IconAliSale: typeof import('~icons/ali/sale')['default']
    IconAliWifi: typeof import('~icons/ali/wifi')['default']
    IconBase: typeof import('./src/components/base/icon/IconBase.vue')['default']
    IconComp: typeof import('./src/components/base/icon/IconComp.vue')['default']
    IconIcBaseline5g: (typeof import('~icons/ic/baseline5g'))['default']
    IconMdilightStar: typeof import('~icons/mdi-light/star')['default']
    IconMdiLightStar: (typeof import('~icons/mdi-light/star'))['default']
    IconMidlightStar: typeof import('~icons/mi/dlight-star')['default']
    IconMidLightStar: (typeof import('~icons/mi/d-light-star'))['default']
    IconSystemBell: (typeof import('~icons/system-uicons/bell'))['default']
    InputTodo: typeof import('./src/components/demo/todo/InputTodo.vue')['default']
    LanguageSelect: typeof import('./src/components/config/LanguageSelect.vue')['default']
    Pagination: typeof import('./src/components/business/table/Pagination.vue')['default']
    RegisterComp: typeof import('./src/components/demo/registerComp/RegisterComp.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/business/table/Table.vue')['default']
    TableLayout: typeof import('./src/components/business/table/TableLayout.vue')['default']
    TodoFilter: typeof import('./src/components/demo/todo/TodoFilter.vue')['default']
    TodoItem: typeof import('./src/components/demo/todo/TodoItem.vue')['default']
    TodoItemReact: typeof import('./src/components/demo/todo/TodoItemReact.vue')['default']
    TodoList: typeof import('./src/components/demo/todo/TodoList.vue')['default']
    TodoListReact: typeof import('./src/components/demo/todo/TodoListReact.vue')['default']
    VmodelChild: typeof import('./src/components/demo/VmodelChild.vue')['default']
    VmodelModifier: typeof import('./src/components/demo/VmodelModifier.vue')['default']
    VmodelModifierPre: typeof import('./src/components/demo/VmodelModifierPre.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
