/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/base/Button.vue')['default']
    DefineModel: typeof import('./src/components/demo/DefineModel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconAliOthers: typeof import('~icons/ali/others')['default']
    IconAliSale: typeof import('~icons/ali/sale')['default']
    IconAliWifi: typeof import('~icons/ali/wifi')['default']
    IconIcBaseline5g: typeof import('~icons/ic/baseline5g')['default']
    IconMdilightStar: typeof import('~icons/mdi-light/star')['default']
    IconMdiLightStar: typeof import('~icons/mdi-light/star')['default']
    IconMidlightStar: typeof import('~icons/mi/dlight-star')['default']
    IconMidLightStar: typeof import('~icons/mi/d-light-star')['default']
    IconSystemBell: typeof import('~icons/system-uicons/bell')['default']
    InputTodo: typeof import('./src/components/demo/todo/InputTodo.vue')['default']
    LanguageSelect: typeof import('./src/components/config/LanguageSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoFilter: typeof import('./src/components/demo/todo/TodoFilter.vue')['default']
    TodoItem: typeof import('./src/components/demo/todo/TodoItem.vue')['default']
    TodoItemReact: typeof import('./src/components/demo/todo/TodoItemReact.vue')['default']
    TodoList: typeof import('./src/components/demo/todo/TodoList.vue')['default']
    TodoListReact: typeof import('./src/components/demo/todo/TodoListReact.vue')['default']
    VmodelChild: typeof import('./src/components/demo/VmodelChild.vue')['default']
    VmodelModifier: typeof import('./src/components/demo/VmodelModifier.vue')['default']
    VmodelModifierPre: typeof import('./src/components/demo/VmodelModifierPre.vue')['default']
  }
}
